@startuml CommandSequence
Wrapper.ts->Wrapper.ts : execute(arguments ...)
Wrapper.ts->CommandService: executeCommand(DTO: CommandDTO)
CommandService->CommandController : httpPost
CommandController->Dispatcher : Dispatch
Dispatcher->Wrapper.cs : ExecuteCommand
Wrapper.cs-->Dispatcher
Dispatcher-->CommandController
CommandController-->CommandService: httpResponse
@enduml
