@startuml
class CommandWrapper {
    -_dto: any
    -_service: any
    +Service: any
    +DTO: any
    +Response: boolean
    +Arguments: any[]
    +Type: Guid
    +Id: Guid
    +getArgument(name: string): any
    +setArgument(name: string, value: string): void
    -{static} _factories: any
    +{static} register(typeId: Guid, factory: CommandWrapperFactory): void
}
class PropertyDTO {
    +Name?: string
    +Value?: string
    +{static} TypeId: Guid
}
class BaseDTO {
    +Id?: Guid
    +Type?: Guid
    +{static} TypeId: Guid
}
class CommandDTO extends BaseDTO {
    +Response?: boolean
    +Arguments?: PropertyDTO[]
    +{static} TypeId: Guid
}
class DeleteAdressBase extends CommandWrapper {
    +Id: Guid
    +Id: Guid
    +Result: any
    +execute(id: Guid): Promise<any>
    +{static} TypeId: Guid
    +{static} IsForMe(dto: CommandDTO): boolean
}
CommandDTO --> "*" PropertyDTO
DeleteAdressBase --> "1" CommandDTO
@enduml